### ISSUE TITLE
Problem with redirection

### ISSUE THREAD

**Issue by tupaxman** [TheLovinator1/discord-embed#74]
Hi,

I think that I have a problem with the redirection of .html files

The upload goes well, all files are created, but when I post the .html link on discord nothing happens. 

However, if I open this link on a browser, it redirects me to `SERVE_DOMAIN/SERVE_DOMAIN/video/test.mp4` instead of `SERVE_DOMAIN/video/test.mp4`

`SERVE_DOMAIN/video/test.mp4` is playing fine on browser, so I suppose that its just a problem from the redirection in the .html

Here is what a generated .html with `embed.example.com` looks like : 

```

    <!DOCTYPE html>
    <html>
    <!-- Generated at 2023-04-05 19:58:09 -->
    <head>
        <meta property="og:type" content="video.other">
        <meta property="twitter:player" content="i.example.com/video/test.mp4">
        <meta property="og:video:type" content="text/html">
        <meta property="og:video:width" content="1920">
        <meta property="og:video:height" content="1080">
        <meta name="twitter:image" content="i.example.com/test.mp4.jpg">
        <meta http-equiv="refresh" content="0;url=i.example.com/video/test.mp4">
    </head>
    </html>
    
```

Do you have an idea about what cause this issue, and how I can fix it ?

Thanks in advance

**Comment by TheLovinator1** [comment]
Does your SERVE_DOMAIN begin with https://?

This is what mine looks like when set to https://i.lovinator.space/

```html
    <!DOCTYPE html>
    <html>
    <!-- Generated at 2023-03-03 02:06:38 -->
    <head>
        <meta property="og:type" content="video.other">
        <meta property="twitter:player" content="https://i.lovinator.space/video/2023.mp4">
        <meta property="og:video:type" content="text/html">
        <meta property="og:video:width" content="1920">
        <meta property="og:video:height" content="1080">
        <meta name="twitter:image" content="https://i.lovinator.space/2023.jpg">
        <meta http-equiv="refresh" content="0;url=https://i.lovinator.space/video/2023.mp4">
    </head>
    </html>
    
```

**Comment by tupaxman** [comment]
Thanks it works now.

In `docker-compose.yml`, I didn't put `https://` before the SERVE_DOMAIN, I changed that and it works now 👌

Unrelated but I get some `ERR_CONNECTION_RESET` errors at upload when the file is too big (I guess), I don't know if the problem comes from my server or from the config of discord-embed

**Comment by TheLovinator1** [comment]
ERR_CONNECTION_RESET is from Chrome so I don't think that is my fault? ¯\_(ツ)_/¯

What reverse proxy do you use?

**Comment by tupaxman** [comment]
I use nginx, but yes I guess its a problem from my side since I managed to upload a 1,5GB file at the beginning, but I can't upload a file that is >200MB now...
